import { jsPDF } from "jspdf";
import { useEffect, useState } from "react";
import {
  Bar,
  BarChart,
  CartesianGrid,
  Legend,
  ResponsiveContainer,
  Tooltip,
  XAxis,
  YAxis,
} from "recharts";

const euro = (n) =>
  n.toLocaleString("en-BE", { style: "currency", currency: "EUR" });

function downloadStatement(db) {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  let y = 22;

  doc.setFillColor(10, 47, 107);
  doc.rect(0, 0, pageWidth, 16, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(12);
  doc.text("KBC  ·  Association statement", 14, 10);

  doc.setTextColor(10, 47, 107);
  doc.setFontSize(18);
  doc.text(db.account.name, 14, y);
  y += 8;
  doc.setFontSize(11);
  doc.setTextColor(80);
  doc.text(db.account.iban, 14, y);
  y += 7;
  doc.text(`Chair: ${db.chief.name}`, 14, y);
  y += 7;
  doc.setTextColor(0, 163, 154);
  doc.setFontSize(14);
  doc.text(`Balance  ${euro(db.account.balance)}`, 14, y);
  y += 12;

  doc.setTextColor(10, 47, 107);
  doc.setFontSize(13);
  doc.text("Chair timeline", 14, y);
  y += 7;
  doc.setFontSize(10);
  doc.setTextColor(40);
  db.timeline.forEach((item) => {
    const mark = item.status === "current" ? "  (current)" : "";
    doc.text(`${item.year}  ${item.chiefName}${mark}`, 14, y);
    y += 6;
  });

  y += 6;
  doc.setTextColor(10, 47, 107);
  doc.setFontSize(13);
  doc.text("Income / expenses", 14, y);
  y += 7;
  doc.setFontSize(10);
  doc.setTextColor(40);
  db.monthly.forEach((m) => {
    doc.text(
      `${m.month}    in ${euro(m.in)}    out ${euro(m.out)}`,
      14,
      y
    );
    y += 5.5;
  });

  y += 6;
  if (y > 250) {
    doc.addPage();
    y = 20;
  }
  doc.setTextColor(10, 47, 107);
  doc.setFontSize(13);
  doc.text("Recent transactions", 14, y);
  y += 7;
  doc.setFontSize(10);
  doc.setTextColor(40);
  db.transactions.forEach((tx) => {
    doc.text(`${tx.date}  ${tx.label}`, 14, y);
    doc.text(euro(tx.amount), pageWidth - 14, y, { align: "right" });
    y += 6;
  });

  y += 10;
  doc.setFontSize(8);
  doc.setTextColor(120);
  doc.text("Generated by KBC mandate continuity (proof of concept).", 14, y);

  const slug = db.account.name.toLowerCase().replace(/\s+/g, "-");
  doc.save(`${slug}-statement.pdf`);
}

async function api(path, options) {
  const res = await fetch(path, {
    headers: { "Content-Type": "application/json" },
    ...options,
  });
  if (!res.ok) {
    const err = await res.json().catch(() => ({}));
    throw new Error(err.error || "API error");
  }
  return res.json();
}

export default function App() {
  const [role, setRole] = useState("alice");
  const [db, setDb] = useState(null);
  const [mandate, setMandate] = useState(null);
  const [modal, setModal] = useState(null);
  const [error, setError] = useState("");

  async function refresh() {
    const [account, check] = await Promise.all([
      api("/api/account"),
      api("/api/check-mandate"),
    ]);
    setDb(account);
    setMandate(check);
  }

  useEffect(() => {
    refresh().catch((e) => setError(e.message));
  }, []);

  if (!db || !mandate) {
    return (
      <div className="grid min-h-screen place-items-center text-[#0a2f6b]/50">
        Loading association account…
      </div>
    );
  }

  const people = Object.values(db.people);
  const isChief = db.account.chiefId === role;
  const designatedId = db.handover.designatedChiefId;
  const showBanner =
    isChief &&
    mandate.status === "ending_soon" &&
    db.handover.status === "idle";
  const showOutgoingWait = isChief && db.handover.status === "pending_incoming";
  const showIncoming =
    role === designatedId && db.handover.status === "pending_incoming";
  const showHeritage = isChief && db.handover.status === "completed";
  const inviteChannel = db.handover.invite?.channel === "sms" ? "SMS" : "email";

  return (
    <div className="min-h-screen">
      <div className="no-print bg-[#1b1464] px-6 py-1.5 text-right text-xs text-white/80">
        KBC · Proof of concept
      </div>
      <header className="no-print flex flex-wrap items-center justify-between gap-4 border-b border-slate-200 bg-white px-6 py-4">
        <div className="flex items-center gap-3">
          <span className="grid h-9 w-9 place-items-center rounded-full bg-[#00b5e2] text-sm font-bold text-white">
            KBC
          </span>
          <div>
            <p className="text-xs font-medium uppercase tracking-[0.18em] text-[#00a39a]">
              Banking
            </p>
            <h1 className="text-xl font-semibold text-[#0a2f6b]">
              Association mandate continuity
            </h1>
          </div>
        </div>
        <div className="flex flex-wrap items-center gap-3">
          <span className="text-sm text-[#0a2f6b]/70">Sign in as</span>
          <select
            value={role}
            onChange={(e) => setRole(e.target.value)}
            className="rounded-full border border-slate-200 bg-white px-3 py-1.5 text-sm font-medium text-[#0a2f6b]"
          >
            {people.map((p) => (
              <option key={p.id} value={p.id}>
                {p.name} · {p.role}
              </option>
            ))}
          </select>
          <button
            className="rounded-full bg-[#00b5e2] px-4 py-1.5 text-xs font-semibold text-white"
            onClick={async () => {
              await api("/api/reset", { method: "POST" });
              setRole("alice");
              await refresh();
            }}
          >
            Reset demo
          </button>
        </div>
      </header>

      <main className="mx-auto max-w-5xl space-y-5 p-6">
        {error && (
          <p className="rounded-lg bg-red-50 px-4 py-2 text-sm text-red-700">
            {error}
          </p>
        )}

        <section className="rounded-2xl bg-white p-5 shadow-sm">
          <div className="flex flex-wrap items-end justify-between gap-4">
            <div>
              <p className="text-sm text-[#0a2f6b]/50">{db.account.iban}</p>
              <h2 className="text-2xl font-semibold text-[#0a2f6b]">
                {db.account.name}
              </h2>
              <p className="mt-1 text-sm">
                Current chair: <strong>{db.chief.name}</strong>
              </p>
            </div>
            <div className="text-right">
              <p className="text-sm text-[#0a2f6b]/50">Balance</p>
              <p className="text-3xl font-semibold text-[#00a39a]">
                {euro(db.account.balance)}
              </p>
            </div>
          </div>
        </section>

        {showBanner && (
          <section className="rounded-2xl border border-[#00b5e2]/30 bg-white p-5 shadow-sm">
            <p className="text-xs font-semibold uppercase tracking-wide text-[#00a39a]">
              KBC detection · mandate cycle
            </p>
            <h3 className="mt-1 text-xl font-semibold text-[#0a2f6b]">
              Time to prepare the handover
            </h3>
            <p className="mt-2 max-w-2xl text-sm text-[#0a2f6b]/75">
              {db.chief.name}’s mandate is ending soon. There is no member list
              on the account: invite the next chair by name, then email or mobile.
            </p>
            <button
              className="mt-4 rounded-full bg-[#00a39a] px-5 py-2 text-sm font-semibold text-white"
              onClick={() => setModal("invite")}
            >
              Invite a successor
            </button>
          </section>
        )}

        {showOutgoingWait && (
          <section className="rounded-2xl bg-white p-5 shadow-sm">
            <p className="font-medium text-[#0a2f6b]">
              Invitation sent by {inviteChannel} to {db.designated?.name}
            </p>
            <p className="mt-1 text-sm text-[#0a2f6b]/65">
              {db.handover.invite?.to} — waiting for their Itsme / eID
              confirmation (two-party check).
            </p>
          </section>
        )}

        {showIncoming && (
          <section className="rounded-2xl border border-[#00a39a]/40 bg-white p-5 shadow-sm">
            <p className="text-xs font-semibold uppercase tracking-wide text-[#00a39a]">
              {inviteChannel} invitation
            </p>
            <h3 className="mt-1 text-xl font-semibold text-[#0a2f6b]">
              {db.chief.name} is handing you the mandate
            </h3>
            <p className="mt-2 text-sm text-[#0a2f6b]/70">
              Accept to become chair of this account, with the full financial
              memory of the association.
            </p>
            <button
              className="mt-4 rounded-full bg-[#00b5e2] px-5 py-2 text-sm font-semibold text-white"
              onClick={() => setModal("incoming")}
            >
              Accept & take control
            </button>
          </section>
        )}

        {showHeritage && <HeritageDashboard db={db} />}

        {db.account.cardStatus === "in_transit" && isChief && (
          <section className="flex items-center gap-3 rounded-2xl bg-white p-4 shadow-sm">
            <span className="grid h-10 w-10 place-items-center rounded-full bg-[#00b5e2]/15 text-lg">
              💳
            </span>
            <div>
              <p className="font-medium text-[#0a2f6b]">Card on the way</p>
              <p className="text-sm text-[#0a2f6b]/70">
                A new payment card is being issued in the name of {db.chief.name}.
              </p>
            </div>
          </section>
        )}
      </main>

      {modal === "invite" && (
        <InviteModal
          onCancel={() => setModal(null)}
          onSubmit={async (payload) => {
            try {
              setError("");
              const token = { verified: true, provider: "itsme-sim", at: Date.now() };
              await api("/api/handover/initiate", {
                method: "POST",
                body: JSON.stringify({ actorId: role, itsmeToken: token, ...payload }),
              });
              setModal(null);
              await refresh();
            } catch (e) {
              setError(e.message);
              setModal(null);
            }
          }}
        />
      )}

      {modal === "incoming" && (
        <ItsmeModal
          name={db.people[role]?.name}
          onCancel={() => setModal(null)}
          onConfirm={async () => {
            try {
              setError("");
              const token = { verified: true, provider: "itsme-sim", at: Date.now() };
              await api("/api/handover/accept", {
                method: "POST",
                body: JSON.stringify({ actorId: role, itsmeToken: token }),
              });
              setModal(null);
              await refresh();
            } catch (e) {
              setError(e.message);
              setModal(null);
            }
          }}
        />
      )}
    </div>
  );
}

function InviteModal({ onCancel, onSubmit }) {
  const [firstName, setFirstName] = useState("");
  const [lastName, setLastName] = useState("");
  const [channel, setChannel] = useState("email");
  const [email, setEmail] = useState("");
  const [phone, setPhone] = useState("");
  const [itsme, setItsme] = useState(false);

  const canContinue =
    firstName.trim() &&
    lastName.trim() &&
    (channel === "email" ? email.trim() : phone.trim());

  return (
    <div className="no-print fixed inset-0 z-20 grid place-items-center bg-[#0a2f6b]/45 p-4">
      <div className="w-full max-w-lg rounded-2xl bg-white p-6 shadow-xl">
        {!itsme ? (
          <>
            <p className="text-xs font-semibold uppercase tracking-wide text-[#00a39a]">
              Invitation
            </p>
            <h3 className="mt-2 text-xl font-semibold text-[#0a2f6b]">
              Who takes over?
            </h3>
            <p className="mt-2 text-sm text-[#0a2f6b]/70">
              The successor is not on this account yet. Enter their identity and
              send an invitation by email or SMS.
            </p>
            <div className="mt-4 grid gap-3 sm:grid-cols-2">
              <label className="text-sm">
                First name
                <input
                  value={firstName}
                  onChange={(e) => setFirstName(e.target.value)}
                  className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2"
                  placeholder="Bob"
                />
              </label>
              <label className="text-sm">
                Last name
                <input
                  value={lastName}
                  onChange={(e) => setLastName(e.target.value)}
                  className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2"
                  placeholder="Martin"
                />
              </label>
            </div>
            <div className="mt-4 flex gap-2">
              <button
                className={`rounded-full px-3 py-1.5 text-sm font-medium ${
                  channel === "email"
                    ? "bg-[#00a39a] text-white"
                    : "bg-slate-100 text-[#0a2f6b]"
                }`}
                onClick={() => setChannel("email")}
              >
                Email
              </button>
              <button
                className={`rounded-full px-3 py-1.5 text-sm font-medium ${
                  channel === "sms"
                    ? "bg-[#00a39a] text-white"
                    : "bg-slate-100 text-[#0a2f6b]"
                }`}
                onClick={() => setChannel("sms")}
              >
                Mobile
              </button>
            </div>
            {channel === "email" ? (
              <label className="mt-3 block text-sm">
                Email
                <input
                  type="email"
                  value={email}
                  onChange={(e) => setEmail(e.target.value)}
                  placeholder="bob.martin@email.be"
                  className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2"
                />
              </label>
            ) : (
              <label className="mt-3 block text-sm">
                Mobile number
                <input
                  type="tel"
                  value={phone}
                  onChange={(e) => setPhone(e.target.value)}
                  placeholder="+32 470 00 00 00"
                  className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2"
                />
              </label>
            )}
            <div className="mt-5 flex justify-end gap-2">
              <button className="rounded-full px-4 py-2 text-sm" onClick={onCancel}>
                Cancel
              </button>
              <button
                className="rounded-full bg-[#00b5e2] px-4 py-2 text-sm font-semibold text-white disabled:opacity-40"
                disabled={!canContinue}
                onClick={() => setItsme(true)}
              >
                Continue to Itsme
              </button>
            </div>
          </>
        ) : (
          <ItsmeStep
            name="the current chair"
            onCancel={onCancel}
            onConfirm={() =>
              onSubmit({ firstName, lastName, channel, email, phone })
            }
          />
        )}
      </div>
    </div>
  );
}

function ItsmeStep({ name, onCancel, onConfirm }) {
  return (
    <>
      <p className="text-xs font-semibold uppercase tracking-wide text-[#00a39a]">
        Itsme / eID simulation
      </p>
      <h3 className="mt-2 text-xl font-semibold text-[#0a2f6b]">Confirm identity</h3>
      <p className="mt-2 text-sm text-[#0a2f6b]/70">
        In production, the Itsme API would verify {name} in real time. Here a
        token <code>verified: true</code> is sent to the backend.
      </p>
      <div className="mt-5 flex justify-end gap-2">
        <button className="rounded-full px-4 py-2 text-sm" onClick={onCancel}>
          Cancel
        </button>
        <button
          className="rounded-full bg-[#00a39a] px-4 py-2 text-sm font-semibold text-white"
          onClick={onConfirm}
        >
          Confirm with Itsme
        </button>
      </div>
    </>
  );
}

function ItsmeModal({ name, onCancel, onConfirm }) {
  return (
    <div className="no-print fixed inset-0 z-20 grid place-items-center bg-[#0a2f6b]/45 p-4">
      <div className="w-full max-w-md rounded-2xl bg-white p-6 shadow-xl">
        <ItsmeStep name={name} onCancel={onCancel} onConfirm={onConfirm} />
      </div>
    </div>
  );
}

function HeritageDashboard({ db }) {
  return (
    <section className="space-y-5">
      <div className="rounded-2xl bg-white p-5 shadow-sm">
        <div className="mb-4 flex flex-wrap items-center justify-between gap-3">
          <div>
            <h3 className="text-xl font-semibold text-[#0a2f6b]">Heritage dashboard</h3>
            <p className="text-sm text-[#0a2f6b]/70">
              Continuity of memory — you pick up exactly where the previous chair
              left off.
            </p>
          </div>
          <button
            className="no-print rounded-full border border-[#00a39a] px-4 py-2 text-sm text-[#00a39a]"
            onClick={() => downloadStatement(db)}
          >
            Download statement PDF
          </button>
        </div>
        <div className="h-72">
          <ResponsiveContainer width="100%" height="100%">
            <BarChart data={db.monthly} barSize={16}>
              <CartesianGrid strokeDasharray="3 3" />
              <XAxis dataKey="month" />
              <YAxis />
              <Tooltip />
              <Legend />
              <Bar dataKey="in" name="Income" fill="#00a39a" isAnimationActive={false} />
              <Bar dataKey="out" name="Expenses" fill="#00b5e2" isAnimationActive={false} />
            </BarChart>
          </ResponsiveContainer>
        </div>
      </div>

      <div className="grid gap-5 md:grid-cols-2">
        <div className="rounded-2xl bg-white p-5 shadow-sm">
          <h4 className="font-semibold text-[#0a2f6b]">Chair timeline</h4>
          <ol className="mt-4 space-y-3">
            {db.timeline.map((item) => (
              <li key={item.year + item.chiefName} className="flex items-center gap-3">
                <span
                  className={`h-3 w-3 rounded-full ${
                    item.status === "current" ? "bg-[#00b5e2]" : "bg-[#00a39a]/35"
                  }`}
                />
                <span className="w-12 text-sm text-[#0a2f6b]/50">{item.year}</span>
                <span className="font-medium">{item.chiefName}</span>
                {item.status === "current" && (
                  <span className="rounded-full bg-[#e8f7f6] px-2 py-0.5 text-xs text-[#00a39a]">
                    Me
                  </span>
                )}
              </li>
            ))}
          </ol>
        </div>

        <div className="rounded-2xl bg-white p-5 shadow-sm">
          <h4 className="font-semibold text-[#0a2f6b]">Recent transactions</h4>
          <ul className="mt-4 divide-y">
            {db.transactions.map((tx) => (
              <li key={tx.date + tx.label} className="flex justify-between py-2 text-sm">
                <span>
                  <span className="text-[#0a2f6b]/50">{tx.date}</span> · {tx.label}
                </span>
                <span className={tx.amount < 0 ? "text-[#0a2f6b]" : "text-[#00a39a]"}>
                  {euro(tx.amount)}
                </span>
              </li>
            ))}
          </ul>
        </div>
      </div>
    </section>
  );
}
